#!/bin/sh

xset b off &
xset -dpms &
xset s off &
picom --experimental-backends --backend glx --blur-method dual_kawase --menu-opacity=1 --fade-in-step=1 --fade-out-step=1 --fade-delta=0 &
xsetroot -cursor_name left_ptr &
~/.fehbg &
setxkbmap -option "grp:win_space_toggle" -layout "us,ru" &
polybar &

bspc config focused_border_color "#69AADB" 
bspc config normal_border_color "#A8CAE3"

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
